services:
  # --- DATABASE ---
  db:
    # Nama container (opsional, tapi memudahkan referensi)
    container_name: todo-db
    # Mengunduh image database PostgreSQL 15 versi Alpine (versi ringan)
    image: postgres:15-alpine
    # Restart secara otomatis jika container crash, tapi tidak restart jika kita matikan manual
    restart: unless-stopped
    # Menghubungkan port 5432 di host ke port 5432 di container
    ports:
      - "${DB_PORT}:5432"
    # Ambil konfigurasi username, password, dan nama database dari file .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # Membuat folder khusus untuk penyimpanan data database agar tidak hilang saat container dihapus
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Menggunakan network 'todo-network' untuk komunikasi antar container
    networks:
      - todo-network

  # --- APLIKASI WEB ---
  web:
    # Nama container (opsional, tapi memudahkan referensi)
    container_name: todo-web
    # Mem-build Image lokal menggunakan instruksi dari Dockerfile (. artinya folder ini)
    build: .
    # Restart secara otomatis jika container crash, tapi tidak restart jika kita matikan manual
    restart: unless-stopped
    # Menghubungkan port 5005 di host ke port 5005 tempat Flask berjalan
    ports:
      - "${APP_PORT}:5005"
    # Ambil konfigurasi dari file .env ke dalam container
    env_file:
      - .env
    # Override DB_HOST agar mengarah ke service db (bukan localhost dari .env)
    environment:
      - DB_HOST=db
    # Memastikan database (db) harus nyala duluan sebelum web (Flask) berjalan
    depends_on:
      - db
    # Mounting folder lokal ke dalam container (hot reloading)
    # volumes:
    #   - .:/app
    # Menggunakan network 'todo-network' untuk komunikasi antar container
    networks:
      - todo-network

# Membuat ruang penyimpanan data (harddisk virtual) di luar container
volumes:
  pgdata:

# Membuat network baru
networks:
  todo-network:
    driver: bridge
