services:
  # --- CONTAINER DATABASE ---
  db:
    # Nama container (opsional, tapi memudahkan referensi)
    container_name: todo-db
    # Mengunduh image database PostgreSQL 15 versi Alpine (versi ringan)
    image: postgres:15-alpine
    # Restart secara otomatis jika container crash, tapi tidak restart jika kita matikan manual
    restart: unless-stopped
    # Menghubungkan port 5432 laptop ke port 5432 container
    ports:
      - "5432:${DB_PORT}"
    # Ambil konfigurasi username, password, dan nama database dari file .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # Membuat folder khusus untuk penyimpanan data database agar tidak hilang saat container dihapus
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- CONTAINER APLIKASI WEB ---
  web:
    # Nama container (opsional, tapi memudahkan referensi)
    container_name: todo-web
    # Mem-build Image lokal menggunakan instruksi dari Dockerfile (. artinya folder ini)
    build: .
    # Restart secara otomatis jika container crash, tapi tidak restart jika kita matikan manual
    restart: unless-stopped
    # Menghubungkan port 5005 laptop ke port 5005 tempat Flask berjalan
    ports:
      - "5005:${APP_PORT}"
    # Ambil konfigurasi database dari file .env ke dalam aplikasi
    environment:
      # --- Konfigurasi Aplikasi ---
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_ENV=${APP_ENV}

      # --- Konfigurasi Database ---
      - DB_PROVIDER=${DB_PROVIDER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db # Mengarahkan koneksi host ke service 'db' (bukan localhost)
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    # Memastikan database (db) harus nyala duluan sebelum web (Flask) berjalan
    depends_on:
      - db

# Membuat ruang penyimpanan data (harddisk virtual) di luar container
volumes:
  pgdata: